require: rubocop-rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/migrate/*
    - db/schema.rb
    - lib/tasks/auto_annotate_models.rake

Style/Documentation:
  Enabled: false
